- name: app
  format: $remote_addr [$time_local] $protocol $status $bytes_received $bytes_sent $session_time $upstream_addr
  source_files:
    - ./test/nginx.log
  static_config:
    app: appgateway
    stack: nonprod
    region: westeurope
  relabel_config: 
    source_labels: 
      - protocol
      - status
    replacement: